version: "3.8"

services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
      args:
        BUILD_DATE: ${BUILD_DATE:-$(date -u +'%Y-%m-%dT%H:%M:%SZ')}
        VCS_REF: ${VCS_REF:-$(git rev-parse --short HEAD)}
    container_name: harakka-backend
    env_file:
      - .env.local # Load at runtime, not build time
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - ALLOWED_ORIGINS=http://localhost:5180,http://harakka-frontend,http://harakka-frontend:80
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s
    networks:
      - harakka-network

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
      args:
        BUILD_DATE: ${BUILD_DATE:-$(date -u +'%Y-%m-%dT%H:%M:%SZ')}
        VCS_REF: ${VCS_REF:-$(git rev-parse --short HEAD)}
        # Frontend will use /api proxy, so this points to localhost from browser
        VITE_API_URL: http://localhost:5180/api
        VITE_SUPABASE_URL: ${SUPABASE_URL}
        VITE_SUPABASE_ANON_KEY: ${SUPABASE_ANON_KEY}
    container_name: harakka-frontend
    env_file:
      - .env.local # Load at runtime, not build time
    restart: unless-stopped
    ports:
      - "5180:80"
    depends_on:
      backend:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost/health"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s
    networks:
      - harakka-network

networks:
  harakka-network:
    driver: bridge
